@baseurl = http://91.197.96.76:8080/api/v1

get {{baseurl}}/courses/
Content-Type: application/json

###

post {{baseurl}}/courses/
Content-Type: application/json

{
    "name": "javacourse",
    "students": [
      {
        "id": 1
      }
    ]
}

###

patch {{baseurl}}/courses/20/
Content-Type: application/json

{
    "name": "new python",
    "students": [
      {
        "id": 1
      }
    ]
}

###
delete {{baseurl}}/courses/23/
Content-Type: application/json

###
get {{baseurl}}/courses/23/
Content-Type: application/json


###

post {{baseurl}}/courses/
Content-Type: application/json

{
    "name": "Rust",
    "students": [7]
}

###

post {{baseurl}}/student/
Content-Type: application/json

{
    "name": "Maximus"
}

###
get {{baseurl}}/student/
Content-Type: application/json