name: ci dj_testing project

on: 
  push: 
    branches: [ 'main' ]

jobs:
  testing:
    runs-on: ubuntu-22.04
    env: 
      DB_PASS: ${{ secrets.PSQLPASS }}
    services:
      postgres_main:
        image: postgres:12
        env:
          POSTGRES_DB: djangotesting
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD:  ${{ env.DB_PASS }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: check changes
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12'

      - name: requirements setup
        run: pip install -r requirements-dev.txt

      - name: linting
        run: flake8 students/ --exclude students/migrations

      - name: tests
        run: pytest
        env:
          PSQLPASS: ${{ env.DB_PASS }}
        